name: Publish

on:
    push:
        branches: [main, release/**]

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18.14.2
                  registry-url: https://registry.npmjs.org/
            - run: npm ci
            - run: npm run build
            - run: .ci/runChecks.sh
            - run: npx enhanced-publish --if-possible --use-preid-as-tag
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
